### ISSUE TITLE
'make' fails to run 

### ISSUE THREAD

**Issue by adithi16** [nmoran/DoQO#1]
## Describe the bug
`make` fails to run due to a C error

## To Reproduce
1.Ensured PETSC and STEPC is working by make checks on both
2. Completed CMAKE successfully for DoQO  

## Behavior
'make' is interrupted by an error as shown in the screenshot below

## Screenshots
![index](https://user-images.githubusercontent.com/78216921/110366327-21fd3e00-806c-11eb-8aa8-18bf1b2decaa.jpeg)

## Versions of make and C
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

make --version
GNU Make 4.1

**Comment by nmoran** [comment]
This is due to a change in the usage of the PetscOptionsGetString function. I have made some changes in #2 which should fix this.

**Comment by adithi16** [comment]
Thank you for your response. 
We have been able to install DoQo.  
("make" is successfully completed)
But we are unable to execute any input file. 
The following error shows up in the command line once we try to run using the "DoQo" executable in the 'bin' folder of 'DoQo' folder created by us. 

![screenshot](https://user-images.githubusercontent.com/79824047/112799901-95530800-908c-11eb-9973-9edd06c2842a.jpeg)

Let us know how to proceed.

**Comment by nmoran** [comment]
Hi @adithi16 , the issue is that the SLEPc library that was linked against cannot be found. To solve this you must set the `LD_LIBRARY_PATH` environment variable to include the folder that contains this library. This is usually found in the `${SLEPC_DIR}/${PETSC_ARCH}/lib` folder. if you have these variable set. 

Also seems it is looking for version 3.6 but the output in the initial post mentions that it found SLEPc version 3.13.4. Can you clarify which version of SLEPc and PETSc you are using?

**Comment by adithi16** [comment]
1. While installing DoQo initially since it was giving errors, we tried with 3.6 version for both PETSC and SLEPC before your first reply. 
Currently, we have PETSC 3.6.4 and SLEPC 3.6.3.

2. In the ~/. bashrc file, this LD_LIBRARY_PATH has been set to the following:

LD_LIBRARY_PATH="/home/adithi/Project4/petsc-3.6.4/arch-linux2-c-debug/lib:$LD_LIBRARY_PATH"

There is no mention of SLEPC here. 
Could you please let us know what changes to make to load libslepc.so.3.6?

**Comment by nmoran** [comment]
Ok, if you add an additional line here to point to the slepc lib folder it should work. Looking at your path I'm guessing the slepc folder is called something like `/home/adithi/Project4/slepc-3.6.3/arch-linux2-c-debug/lib`?

If so then you would add an additional line to your .bashrc which would read as

```
LD_LIBRARY_PATH="/home/adithi/Project4/slepc-3.6.3/arch-linux2-c-debug/lib:$LD_LIBRARY_PATH
```

**Comment by adithi16** [comment]
It is working now. Thank you very much.
